In [1]:
import pandas as pd

data = {
    "names":["mubeen","ali","mubeen","ahmad","ali","mubeen","ahmad"],
    "colors":["red","green","blue","red","green","blue","red"]
    
}

df = pd.DataFrame(data)
df

names colors
0  mubeen    red
1     ali  green
2  mubeen   blue
3   ahmad    red
4     ali  green
5  mubeen   blue
6   ahmad    red

## one hot encoding with pandas (get dummies)

In [2]:
pd.get_dummies(df,columns=["colors"])

names  colors_blue  colors_green  colors_red
0  mubeen            0             0           1
1     ali            0             1           0
2  mubeen            1             0           0
3   ahmad            0             0           1
4     ali            0             1           0
5  mubeen            1             0           0
6   ahmad            0             0           1

## Drop first column (dummy variable)

In [3]:
pd.get_dummies(df,columns=["colors"],drop_first=True)

names  colors_green  colors_red
0  mubeen             0           1
1     ali             1           0
2  mubeen             0           0
3   ahmad             0           1
4     ali             1           0
5  mubeen             0           0
6   ahmad             0           1

## we are not apply one hot encoding with pandas because pandas are not learn the value means not fixed order 

# one hot encoding with sklearn

In [4]:
col = df.colors
col = pd.DataFrame(col)
col

colors
0    red
1  green
2   blue
3    red
4  green
5   blue
6    red

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(col)

OneHotEncoder()

In [6]:
en_data=ohe.transform(col)
en_data

<7x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

### They return the sparse matrix
* ## toarray() convert sparse to numpy

In [7]:
en_data.toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

## drop first column 

In [8]:
ohe = OneHotEncoder(drop="first")
ohe.fit(col)
ohe.transform(col)

<7x2 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

## Sparse False

In [9]:
ohe = OneHotEncoder(drop="first",sparse=False)
ohe.fit(col)
new = ohe.transform(col)
new

array([[0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.]])

In [10]:
import numpy as np
new = pd.DataFrame(new,dtype=np.int32,columns=["colors green","colors red"])
new

colors green  colors red
0             0           1
1             1           0
2             0           0
3             0           1
4             1           0
5             0           0
6             0           1

## Combined data

In [11]:
edit = np.hstack((df[["names"]].values,new))

In [12]:
edit = pd.DataFrame(edit)
edit.columns = ["names","colors green","colors red"]
edit

names colors green colors red
0  mubeen            0          1
1     ali            1          0
2  mubeen            0          0
3   ahmad            0          1
4     ali            1          0
5  mubeen            0          0
6   ahmad            0          1

## One Hot Encoding with data set

In [13]:
data = pd.read_csv("./CarPrice_Assignment.csv",usecols=["CarName"])
data.head()

CarName
0        alfa-romero giulia
1       alfa-romero stelvio
2  alfa-romero Quadrifoglio
3               audi 100 ls
4                audi 100ls

In [14]:
data = data.tail(11)

In [15]:
data.value_counts()

CarName        
volvo 264gl        2
volvo 244dl        2
volvo 145e (sw)    2
volvo 144ea        2
volvo diesel       1
volvo 246          1
volvo 245          1
dtype: int64

In [16]:
data.CarName.nunique()

7

# One Hot Encoding with pandas

In [17]:
pd.get_dummies(data)

CarName_volvo 144ea  CarName_volvo 145e (sw)  CarName_volvo 244dl  \
194                    0                        1                    0   
195                    1                        0                    0   
196                    0                        0                    1   
197                    0                        0                    0   
198                    0                        0                    0   
199                    0                        0                    0   
200                    0                        1                    0   
201                    1                        0                    0   
202                    0                        0                    1   
203                    0                        0                    0   
204                    0                        0                    0   

     CarName_volvo 245  CarName_volvo 246  CarName_volvo 264gl  \
194                  0                  0                    0   
195                  0                  0                    0   
196                  0                  0                    0   
197                  1                  0                    0   
198                  0                  0                    1   
199                  0                  0                    0   
200                  0                  0                    0   
201                  0                  0                    0   
202                  0                  0                    0   
203                  0                  1                    0   
204                  0                  0                    1   

     CarName_volvo diesel  
194                     0  
195                     0  
196                     0  
197                     0  
198                     0  
199                     1  
200                     0  
201                     0  
202                     0  
203                     0  
204                     0

# Droping

In [18]:
val = pd.get_dummies(data,drop_first=True)
val

CarName_volvo 145e (sw)  CarName_volvo 244dl  CarName_volvo 245  \
194                        1                    0                  0   
195                        0                    0                  0   
196                        0                    1                  0   
197                        0                    0                  1   
198                        0                    0                  0   
199                        0                    0                  0   
200                        1                    0                  0   
201                        0                    0                  0   
202                        0                    1                  0   
203                        0                    0                  0   
204                        0                    0                  0   

     CarName_volvo 246  CarName_volvo 264gl  CarName_volvo diesel  
194                  0                    0                     0  
195                  0                    0                     0  
196                  0                    0                     0  
197                  0                    0                     0  
198                  0                    1                     0  
199                  0                    0                     1  
200                  0                    0                     0  
201                  0                    0                     0  
202                  0                    0                     0  
203                  1                    0                     0  
204                  0                    1                     0

In [19]:
val.columns

Index(['CarName_volvo 145e (sw)', 'CarName_volvo 244dl', 'CarName_volvo 245',
       'CarName_volvo 246', 'CarName_volvo 264gl', 'CarName_volvo diesel'],
      dtype='object')

# Appling with Sklearn

In [20]:
from sklearn.preprocessing import OneHotEncoder
end = OneHotEncoder()

data = pd.read_csv("./CarPrice_Assignment.csv",usecols=["CarName"])
data = data.tail(11)
data = pd.DataFrame(data,columns=["CarName"])
data

CarName
194  volvo 145e (sw)
195      volvo 144ea
196      volvo 244dl
197        volvo 245
198      volvo 264gl
199     volvo diesel
200  volvo 145e (sw)
201      volvo 144ea
202      volvo 244dl
203        volvo 246
204      volvo 264gl

In [21]:
end.fit(data)

OneHotEncoder()

In [22]:
enc_data=end.transform(data)
enc_data

<11x7 sparse matrix of type '<class 'numpy.float64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [23]:
enc_data.toarray()

array([[0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

# Dropping

In [24]:
Ds = OneHotEncoder(drop="first",sparse=False)
Ds.fit(data)

OneHotEncoder(drop='first', sparse=False)

In [25]:

DS = Ds.transform(data)
DS

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [26]:
D = pd.DataFrame(DS,columns=val.columns,dtype=int)
D

CarName_volvo 145e (sw)  CarName_volvo 244dl  CarName_volvo 245  \
0                         1                    0                  0   
1                         0                    0                  0   
2                         0                    1                  0   
3                         0                    0                  1   
4                         0                    0                  0   
5                         0                    0                  0   
6                         1                    0                  0   
7                         0                    0                  0   
8                         0                    1                  0   
9                         0                    0                  0   
10                        0                    0                  0   

    CarName_volvo 246  CarName_volvo 264gl  CarName_volvo diesel  
0                   0                    0                     0  
1                   0                    0                     0  
2                   0                    0                     0  
3                   0                    0                     0  
4                   0                    1                     0  
5                   0                    0                     1  
6                   0                    0                     0  
7                   0                    0                     0  
8                   0                    0                     0  
9                   1                    0                     0  
10                  0                    1                     0

# Apply Threshold

In [27]:
data = pd.read_csv("./CarPrice_Assignment.csv",usecols=["CarName"])
data

CarName
0          alfa-romero giulia
1         alfa-romero stelvio
2    alfa-romero Quadrifoglio
3                 audi 100 ls
4                  audi 100ls
..                        ...
200           volvo 145e (sw)
201               volvo 144ea
202               volvo 244dl
203                 volvo 246
204               volvo 264gl

[205 rows x 1 columns]

In [28]:
count = data.value_counts()
count

CarName          
toyota corona        6
toyota corolla       6
peugeot 504          6
subaru dl            4
honda civic          3
                    ..
plymouth valiant     1
porcshce panamera    1
porsche boxter       1
porsche macan        1
Nissan versa         1
Length: 147, dtype: int64

In [29]:
data.CarName.nunique()

147

In [30]:
threshold = 6

In [31]:
set_ = count[count <= threshold].index

In [32]:
data

CarName
0          alfa-romero giulia
1         alfa-romero stelvio
2    alfa-romero Quadrifoglio
3                 audi 100 ls
4                  audi 100ls
..                        ...
200           volvo 145e (sw)
201               volvo 144ea
202               volvo 244dl
203                 volvo 246
204               volvo 264gl

[205 rows x 1 columns]

In [33]:
pd.get_dummies(data["CarName"].replace(set_,"uncomon"))

uncomon
0          1
1          1
2          1
3          1
4          1
..       ...
200        1
201        1
202        1
203        1
204        1

[205 rows x 1 columns]

In [34]:
newdata = pd.get_dummies(data.CarName.replace(set_,"uncommon"))

# Store all value in uncommon whose range are shorter than and equal to 6

In [35]:
newdata

uncommon
0           1
1           1
2           1
3           1
4           1
..        ...
200         1
201         1
202         1
203         1
204         1

[205 rows x 1 columns]